trigger:
- master

# pr:
# - master

pool:
  name: 'bedrock-pool'

steps:

  - script: |
      echo $(pwd)
      ls -la
      NOW=$(date +"%m-%d-%Y-%H-%M-%S")
      touch "README-$NOW.md"
      ls -la
      echo "az cli version" 
      az --version

      echo "fabrikate version" 
      fab version

      echo "helm version"
      helm init --client-only
      helm version
      
      echo "spk version"
      spk --version

      echo "terraform version"
      terraform version

      echo "Can we access ENV VARS?"
      echo $AZP_URL
      echo $AZP_POOL
      echo $AZP_AGENT_NAME
      echo $ARM_SUBSCRIPTION_ID
      
      # echo "Can we access build.sh?"
      # bedrock_build 1
    displayName: "Echo stuff"