trigger:
- master

# pr:
# - master

pool:
  name: 'bedrock-pool'

steps:

  - script: |
      echo "az cli version" 
      az --version

      echo "fabrikate version" 
      fab version

      echo "helm version"
      helm init --client-only
      helm version
      
      echo "spk version"
      spk --version

      echo "terraform version"
      terraform version

      echo "Can we access build.sh?"
      bedrock_build
    displayName: "Echo stuff"