trigger: none

variables:
- group: 'agent-build-vg' 

steps:
- bash: |
    # Login to Azure 
    echo "az login --service-principal --username $(SP_CLIENT_ID) --password $(SP_CLIENT_PASS) --tenant $(TENANT_ID)"
    az login --service-principal --username "$(SP_CLIENT_ID)" --password "$(SP_CLIENT_PASS)" --tenant "$(TENANT_ID)"

    az acr login --name $(ACR_NAME)
    az acr build -r $(ACR_NAME) --image bedrock-build-agent:dev .
  displayName: "Docker Build to ACR"
  failOnStderr: true
