trigger: none

variables:
- group: 'agent-build-vg' 

stages:
- stage: provision_agent
  jobs:
  - job: acr_build_publish
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - bash: |
        # Login to Azure 
        echo "az login --service-principal --username $(SP_CLIENT_ID) --password $(SP_CLIENT_PASS) --tenant $(TENANT_ID)"
        az login --service-principal --username "$(SP_CLIENT_ID)" --password "$(SP_CLIENT_PASS)" --tenant "$(TENANT_ID)"
        
        az acr login --name $(ACR_NAME)
        az acr build -r $(ACR_NAME) --image bedrock-build-agent:dev .

        AZDO_PAT=$(AZDO_PAT)
        SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)
        TENANT_ID=$(TENANT_ID)
        SP_CLIENT_ID=$(SP_CLIENT_ID)
        SP_CLIENT_PASS=$(SP_CLIENT_PASS)
        
        bash ./setup-build-agent.sh
      displayName: "Docker build"
      failOnStderr: true
      # env:
      #   FUNC_SCRIPT: $(FUNC_SCRIPT)
      #   TEST_SCRIPT2: $(TEST_SCRIPT2)
    # - bash: |
    #     # Login to Azure 
    #     echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
    #     az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
        
        
    #   displayName: "Provision_Build_Agent"
    #   failOnStderr: true